version: "3"

services:
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                     C O D E I G N I T E R  v4.0.3                        #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
    codeigniter4:
        image: atsanna/codeigniter4:latest
        container_name: 'codeigniter4'
        ports:
          - 8001:80
        links:
          - ${DB_HOST}
        volumes:
          - ./src/www:/var/www/html

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                               M Y S Q L                                  #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#               
    codeigniter4_mysql:
        image: mysql:8.0.20
        container_name: ${DB_HOST}
        ports:
          - 3306:3306
        volumes:
          - ./src/mysql:/var/lib/mysql
          - ./src/logs/mysql:/var/log/mysql
        environment:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_USER: ${DB_USER}
          MYSQL_PASSWORD: ${DB_PASSWORD}

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                         P H P M Y A D M I N                              #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#             
    codeigniter4_phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.2
        container_name: ${DB_DATABASE}
        links:
          - ${DB_HOST}
        environment:
          PMA_HOST: ${DB_HOST}
          PMA_PORT: 3306
        ports:
          - 8002:80
        volumes:
          - ./src/sessions:/sessions
